//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        public int C_Order_id { get; set; }
        public string C_Food_id { get; set; }
        public string C_Staff_id { get; set; }
        public string C_Shift_id { get; set; }
        public Nullable<System.DateTime> C_Order_date { get; set; }
    
        public virtual MENU MENU { get; set; }
        public virtual SPLIT_TIME SPLIT_TIME { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
