//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPLIT_TIME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPLIT_TIME()
        {
            this.ORDERS = new HashSet<ORDERS>();
            this.SPLIT_SHIFTS = new HashSet<SPLIT_SHIFTS>();
        }
    
        public string C_Shift_id { get; set; }
        public string C_Shift_name { get; set; }
        public string C_Time_in { get; set; }
        public System.DateTime C_Time_out { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS> ORDERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPLIT_SHIFTS> SPLIT_SHIFTS { get; set; }
    }
}
