//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER
    {
        public string C_Supplier_id { get; set; }
        public string C_Supplier_name { get; set; }
        public string C_Supplier_phone { get; set; }
        public string C_Supplier_address { get; set; }
        public string C_Material_id { get; set; }
        public Nullable<int> C_Quantity_S { get; set; }
        public string C_Unit { get; set; }
    
        public virtual INGREDIENT INGREDIENT { get; set; }
    }
}
