//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPLIT_SHIFTS
    {
        public string C_Shift_id { get; set; }
        public string C_Staff_id { get; set; }
        public Nullable<int> C_month { get; set; }
    
        public virtual SPLIT_TIME SPLIT_TIME { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
