//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STAFF()
        {
            this.LOGIN = new HashSet<LOGIN>();
            this.ORDERS = new HashSet<ORDERS>();
            this.SPLIT_SHIFTS = new HashSet<SPLIT_SHIFTS>();
        }
    
        public string C_Staff_id { get; set; }
        public string C_Staff_name { get; set; }
        public Nullable<System.DateTime> C_Birthday { get; set; }
        public Nullable<bool> C_Gender { get; set; }
        public string C_Identity_card { get; set; }
        public string C_Position { get; set; }
        public string C_phone_number { get; set; }
        public string C_Ward { get; set; }
        public string C_District { get; set; }
        public string C_City { get; set; }
        public string C_Department_id { get; set; }
        public string C_Face_id { get; set; }
        public string C_Image { get; set; }
        public string C_Ethnic { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual FACE FACE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGIN> LOGIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS> ORDERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPLIT_SHIFTS> SPLIT_SHIFTS { get; set; }
    }
}
